islandora-1848.  Unmanged file cleanup
Islandora/islandora_ocr pull request #73
Opened 2016-12-01 17:12 UTC by ajstanley

**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1848)
# What does this Pull Request do?
Removes unmanaged files after OCR datastream update

# What's new?
Deletion of tmp source file after use.
# How should this be tested?

Open /tmp directory and note all files.

Go to page of existing book.
Navigate to manage/page/perform ocr
Click perform ocr
When confirmation of OCR creation has appeared on your screen check /tmp directory  There should be no new files there.

There should be no Notices in the browser

# Interested parties
@Islandora/7-x-1-x-committers

2017-02-16 17:22 UTC, DiegoPino requested changes
I think two other temporary files are left behind. Could need some extra review.

2017-02-16 17:22 UTC, DiegoPino commented on includes/derivatives.inc
> -  $files = array_filter(array($source_file, $ocr_file, $hocr_file));
Hi @ajstanley. Cool. I see why removing this
```PHP
 array_filter(array($source_file, $ocr_file, $hocr_file));
````
makes sense (none of those were defined at all!). 
What I don't see is how you manage to remove (unlink) the [files created indirectly via islandora_ocr_generate_derivatives()](https://github.com/ajstanley/islandora_ocr/blob/d57b4915055905075db33c2eee4da50c09c3cb09/includes/derivatives.inc#L184-L185) when calling [islandora_ocr_create_ocr](https://github.com/ajstanley/islandora_ocr/blob/d57b4915055905075db33c2eee4da50c09c3cb09/includes/derivatives.inc#L20-L38)  and [islandora_ocr_create_hocr](https://github.com/ajstanley/islandora_ocr/blob/d57b4915055905075db33c2eee4da50c09c3cb09/includes/derivatives.inc#L52-L93)

Should that be managed here, after returning or is that already managed somewhere else?

2017-02-23 21:44 UTC, ajstanley commented on includes/derivatives.inc
> -  $files = array_filter(array($source_file, $ocr_file, $hocr_file));
Sorry - should have answered this sooner.  The temp files are passed to islandora_ocr_update_datastreams, and are dealt with [here](https://github.com/ajstanley/islandora_ocr/blob/7.x/includes/derivatives.inc#L465)

2017-02-23 22:30 UTC, DiegoPino approved these changes

2017-02-23 22:35 UTC, merged