Islandora 2395: Hook for Overwriting Human Readable Language Names
Islandora/islandora_ocr pull request #98
Opened 2019-03-01 23:30 UTC by megwill4268

ISLANDORA-2395: https://jira.duraspace.org/browse/ISLANDORA-2395

A hook that allows the human readable language names to be overwritten so users can define their own needed languages.

Related to closed pull request #93

I do have a CLA on file:
https://github.com/Islandora/islandora/wiki/Contributor-License-Agreements

2019-03-07 19:35 UTC, whikloj commented
Hi @megwill4268, just wondering if there was a reason you closed this work? It seemed to be good work towards the associated ticket. Let me know.

2019-03-08 00:20 UTC, megwill4268 commented
Hi @whikloj it was failing the travis ci tests so I retracted it. I'll re-open it. I haven't gotten a chance to see what in syntax wasn't passing the checks.

2019-03-08 14:15 UTC, bondjimbond commented
@megwill4268 Looks like this may be a problem with the .travis.yml file and not your code. Are other pulls to islandora_ocr failing too? I know islandora_scholar is having this problem.

2019-03-11 13:19 UTC, whikloj commented
@megwill4268 looks like you need a space as described [here](https://travis-ci.org/Islandora/islandora_ocr/jobs/503377327#L636), normally this is because you have 
```
function someFunction(){
```
and it wants
```
function someFunction() {
```

@bondjimbond due to https://github.com/Islandora/islandora/pull/714 a lot of modules need a lot of love to fix outstanding issues now that we have updated code sniffer. That could be the issue with islandora_scholar as well.

2019-03-13 15:33 UTC, megwill4268 commented
@whikloj looks like that fixed it :)

2019-03-14 22:03 UTC, whikloj requested changes
Works out of the box, but I ran into some issues when implementing the hook.

2019-03-14 22:03 UTC, whikloj commented on includes/utilities.inc
> +    if (is_null($language_names)) {
[module_invoke_all](https://api.drupal.org/api/drupal/includes%21module.inc/function/module_invoke_all/7.x) is going to return an array and in the default case an empty one. So you should probably do something like
```
if (count($language_names) == 0) {
```

2019-03-14 22:03 UTC, whikloj commented on islandora_ocr.api.php
> +function hook_get_ocr_tesseract_languages() {
The hook name should have the module name in it, so I would change this to `hook_islandora_ocr_get_ocr_tesseract_languages()`. It is a mouthful, but I think it is required.

2019-03-14 22:03 UTC, whikloj commented on includes/utilities.inc
> +    $language_names = module_invoke_all('get_ocr_tesseract_languages');
Based on the comment I left in the `api.php` document, you'll also need to change the name of the hook here.

2019-03-14 22:16 UTC, whikloj commented
I'll also note that the `module_invoke_all` returns an array with multiple strings for each language code.
For example:

if I implement this hook in modules _example1_ and _example2_. Where example1 always returns the word "example1" and example2 always returns "example2".

The value of `$language_names` [here](https://github.com/Islandora/islandora_ocr/pull/98/files#diff-2d69368f59ba81d5635cd8274dd66090R101) is
```
array
   'eng' => array(
      'example1',
      'example2',
   ),
   'fra' => array(
      'example1',
      'example2',
   ),
);
```

So we might need to pull only the first returned value (First hook wins) or loop through implementers and overwrite existing values (Last hook wins).

2019-06-28 21:33 UTC, whikloj commented
@megwill4268 are you able to move forward with this?

2019-07-11 18:46 UTC, DonRichards commented
@megwill4268 Are you able to make those requested changes?

2019-07-12 21:37 UTC, megwill4268 commented
I have not had time to work on this. Also have wondered with Islandora 8 if
it was worth the effort anymore.

On Thu, Jul 11, 2019 at 1:46 PM Don Richards <notifications@github.com>
wrote:

> @megwill4268 <https://github.com/megwill4268> Are you able to make those
> requested changes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Islandora/islandora_ocr/pull/98?email_source=notifications&email_token=ADH7WBYUCRZEVWJ3NGUWLTLP655Y3A5CNFSM4G3H7QIKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZXUCOY#issuecomment-510607675>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ADH7WB2L4IDWVVSJVVUOUE3P655Y3ANCNFSM4G3H7QIA>
> .
>

2025-07-29 13:47 UTC, closed without merging